services:
  db:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    working_dir: /app/autodealer_backend
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  flower:
    build: .  # Используем тот же Dockerfile, что и для основного приложения
    command: >
      sh -c "pip install flower && 
      celery -A autodealer_backend.celery_app flower --port=5555"
    volumes:
      - .:/app
    working_dir: /app/autodealer_backend
    environment:
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=config.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - web
  celery-worker:
    build: .
    command: celery -A autodealer_backend.celery_app worker --loglevel=info
    volumes:
      - .:/app
    working_dir: /app/autodealer_backend
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db
  celery-beat:
    build: .
    command: celery -A autodealer_backend.celery_app beat --loglevel=info
    volumes:
      - .:/app
    working_dir: /app/autodealer_backend
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

volumes:
  postgres_data: