# Generated by Django 5.2.4 on 2025-08-19 18:55

import datetime

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cars", "0003_remove_car_dealer_remove_car_supplier_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("official", "Официальный дистрибьютор"),
                            ("parallel", "Параллельный импорт"),
                            ("used", "Поставщик б/у авто"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year_established", models.PositiveIntegerField()),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True)),
                ("contact_person", models.CharField(max_length=100)),
                (
                    "average_delivery_time",
                    models.PositiveIntegerField(
                        default=14, help_text="Средний срок поставки в днях"
                    ),
                ),
                (
                    "discount_for_dealers",
                    models.PositiveIntegerField(
                        default=0, help_text="Базовая скидка для дилеров (%)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "supplier"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_brand", models.CharField(blank=True, max_length=50)),
                ("raw_model", models.CharField(blank=True, max_length=50)),
                (
                    "raw_specs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Полные характеристики в JSON (если нет CarModel)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Цена за единицу в USD",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "quantity_available",
                    models.PositiveIntegerField(
                        default=1, help_text="Доступное количество"
                    ),
                ),
                (
                    "discount_percent",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Процент скидки (0-100)",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("valid_from", models.DateField(default=django.utils.timezone.now)),
                ("valid_to", models.DateField(default=datetime.date(2025, 9, 18))),
                (
                    "delivery_days",
                    models.PositiveIntegerField(
                        default=14,
                        help_text="Срок поставки в днях",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "is_new",
                    models.BooleanField(default=True, help_text="Новый (не б/у)"),
                ),
                (
                    "warranty_months",
                    models.PositiveIntegerField(
                        default=24, help_text="Гарантия в месяцах"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_offers",
                        to="cars.carmodel",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение поставщика",
                "verbose_name_plural": "Предложения поставщиков",
                "ordering": ["price"],
            },
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["name"], name="suppliers_s_name_6277a9_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["country", "is_active"], name="suppliers_s_country_353e5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplieroffer",
            index=models.Index(
                fields=["valid_from", "valid_to"], name="suppliers_s_valid_f_160d21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplieroffer",
            index=models.Index(fields=["price"], name="suppliers_s_price_e472b2_idx"),
        ),
        migrations.AddIndex(
            model_name="supplieroffer",
            index=models.Index(
                fields=["supplier", "is_active"], name="suppliers_s_supplie_2b8ca9_idx"
            ),
        ),
    ]
