# Generated by Django 5.2.5 on 2025-08-20 13:36

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplieroffer",
            name="valid_to",
            field=models.DateField(default=datetime.date(2025, 9, 19)),
        ),
    ]
