# Generated by Django 5.2.5 on 2025-11-28 20:33

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0002_alter_supplieroffer_valid_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplieroffer",
            name="valid_to",
            field=models.DateField(default=datetime.date(2025, 12, 28)),
        ),
    ]
