# Generated by Django 5.2.5 on 2025-08-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_delete_car_delete_promotion_and_more"),
        ("promotion", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="promotioncar",
            unique_together={("promotion", "car_model")},
        ),
        migrations.AlterModelTable(
            name="promotioncar",
            table="promotion_car_relations",
        ),
    ]
