# Generated by Django 5.2.4 on 2025-08-19 18:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_remove_car_dealer_remove_car_supplier_and_more"),
        ("dealers", "0003_dealerstock_alter_dealer_options_and_more"),
        ("deals", "0003_alter_deal_options_alter_offer_options_and_more"),
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deal",
            options={
                "ordering": ["-date"],
                "verbose_name": "Сделка",
                "verbose_name_plural": "Сделки",
            },
        ),
        migrations.AlterModelOptions(
            name="offer",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Оффер",
                "verbose_name_plural": "Офферы",
            },
        ),
        migrations.RemoveField(
            model_name="deal",
            name="car",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="is_active",
        ),
        migrations.AddField(
            model_name="deal",
            name="deal_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Покупка у поставщика"),
                    ("sale", "Продажа клиенту"),
                ],
                default="purchase",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deal",
            name="dealer_stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="dealers.dealerstock",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deal",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to="deals.offer",
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="deal",
            name="supplier_offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to="suppliers.supplieroffer",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="expiry_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="offer",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="preferred_dealers",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "dealer"},
                related_name="received_offers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "customer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="dealer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "dealer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="car_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="cars.carmodel",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="customer",
            field=models.ForeignKey(
                limit_choices_to={"role": "customer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="max_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "На рассмотрении"),
                    ("accepted", "Принято"),
                    ("rejected", "Отклонено"),
                    ("expired", "Просрочено"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["deal_type", "date"], name="deals_deal_deal_ty_5945a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["customer", "is_completed"],
                name="deals_deal_custome_b28047_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["status", "expiry_date"], name="deals_offer_status_091217_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["customer", "is_active"], name="deals_offer_custome_2a1342_idx"
            ),
        ),
    ]
