# Generated by Django 5.2.4 on 2025-08-19 18:55

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("deals", "0004_alter_deal_options_alter_offer_options_and_more"),
        ("users", "0005_user_verification_token_alter_user_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Баланс в USD", max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Покупатель"),
                    ("dealer", "Дилер"),
                    ("supplier", "Поставщик"),
                    ("admin", "Администратор"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={
                    "blank": "Email is required",
                    "null": "Email is required",
                },
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="verification_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_active"], name="users_user_role_e1ec1a_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
