# Generated by Django 5.2.5 on 2025-11-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_customer_user_alter_user_options_user_address_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
