# Generated by Django 5.2.4 on 2025-07-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealer',
            options={'ordering': ['id']},
        ),
    ]
