# Generated by Django 5.2.4 on 2025-08-19 18:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_remove_car_dealer_remove_car_supplier_and_more"),
        ("dealers", "0002_alter_dealer_options"),
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DealerStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vin", models.CharField(blank=True, max_length=17, unique=True)),
                ("mileage", models.PositiveIntegerField(default=0)),
                ("color", models.CharField(max_length=30)),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "Новый"), ("used", "Б/у"), ("demo", "Демо")],
                        default="new",
                        max_length=4,
                    ),
                ),
                ("is_sold", models.BooleanField(default=False)),
                ("arrival_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Автомобиль в наличии",
                "verbose_name_plural": "Автомобили в наличии",
                "ordering": ["-arrival_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="dealer",
            options={
                "ordering": ["name"],
                "verbose_name": "Автосалон",
                "verbose_name_plural": "Автосалоны",
            },
        ),
        migrations.RemoveField(
            model_name="dealer",
            name="preferred_car_brands",
        ),
        migrations.RemoveField(
            model_name="dealer",
            name="preferred_car_characteristics",
        ),
        migrations.AddField(
            model_name="dealer",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="dealer",
            name="contact_person",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Контактное лицо"
            ),
        ),
        migrations.AddField(
            model_name="dealer",
            name="dealer_type",
            field=models.CharField(
                choices=[
                    ("premium", "Премиальный"),
                    ("standard", "Стандартный"),
                    ("discount", "Дискаунтер"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dealer",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Почта"
            ),
        ),
        migrations.AddField(
            model_name="dealer",
            name="legal_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="dealer",
            name="phone",
            field=models.CharField(default=375884848398, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dealer",
            name="preferred_car_models",
            field=models.ManyToManyField(
                blank=True,
                help_text="Предпочитаемые модели автомобилей",
                related_name="preferred_by_dealers",
                to="cars.carmodel",
            ),
        ),
        migrations.AddField(
            model_name="dealer",
            name="user",
            field=models.OneToOneField(
                default=1,
                limit_choices_to={"role": "dealer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dealer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dealer",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="dealer",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Баланс в USD",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddIndex(
            model_name="dealer",
            index=models.Index(fields=["name"], name="dealers_dea_name_81be76_idx"),
        ),
        migrations.AddIndex(
            model_name="dealer",
            index=models.Index(
                fields=["location", "is_active"], name="dealers_dea_locatio_cc9e5d_idx"
            ),
        ),
        migrations.AddField(
            model_name="dealerstock",
            name="car_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dealer_inventory",
                to="cars.carmodel",
            ),
        ),
        migrations.AddField(
            model_name="dealerstock",
            name="dealer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dealer_stock",
                to="dealers.dealer",
            ),
        ),
        migrations.AddField(
            model_name="dealerstock",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="suppliers.supplier",
            ),
        ),
    ]
