# Generated by Django 5.2.4 on 2025-08-19 18:55

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_alter_car_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="dealer",
        ),
        migrations.RemoveField(
            model_name="car",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="cars",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="dealer",
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(db_index=True, max_length=50)),
                ("model", models.CharField(db_index=True, max_length=50)),
                ("generation", models.CharField(blank=True, max_length=50)),
                (
                    "production_start",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                (
                    "production_end",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "engine_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Бензин"),
                            ("diesel", "Дизель"),
                            ("electric", "Электрический"),
                            ("hybrid", "Гибрид"),
                        ],
                        default="petrol",
                        max_length=20,
                    ),
                ),
                (
                    "engine_volume",
                    models.DecimalField(decimal_places=1, default=2.0, max_digits=3),
                ),
                ("power", models.PositiveIntegerField(default=150)),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("manual", "Механическая"),
                            ("automatic", "Автоматическая"),
                            ("robot", "Роботизированная"),
                            ("cvt", "Вариатор"),
                        ],
                        default="automatic",
                        max_length=20,
                    ),
                ),
                (
                    "drive_type",
                    models.CharField(
                        choices=[
                            ("fwd", "Передний"),
                            ("rwd", "Задний"),
                            ("awd", "Полный"),
                        ],
                        default="fwd",
                        max_length=20,
                    ),
                ),
                (
                    "fuel_consumption",
                    models.DecimalField(decimal_places=1, default=8.5, max_digits=4),
                ),
                ("length", models.PositiveIntegerField(default=4500)),
                ("width", models.PositiveIntegerField(default=1800)),
                ("height", models.PositiveIntegerField(default=1500)),
                ("weight", models.PositiveIntegerField(default=1500)),
                (
                    "body_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        default=list,
                        help_text="Типы кузова (седан, универсал и т.д.)",
                        size=None,
                    ),
                ),
                ("seats", models.PositiveSmallIntegerField(default=5)),
                ("doors", models.PositiveSmallIntegerField(default=4)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Модель автомобиля",
                "verbose_name_plural": "Модели автомобилей",
                "ordering": ["brand", "model", "production_start"],
                "unique_together": {("brand", "model", "generation")},
            },
        ),
        migrations.CreateModel(
            name="CarFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("safety", "Безопасность"),
                            ("comfort", "Комфорт"),
                            ("multimedia", "Мультимедиа"),
                            ("exterior", "Экстерьер"),
                            ("interior", "Интерьер"),
                        ],
                        default="comfort",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "is_standard",
                    models.BooleanField(
                        default=False, help_text="Входит в базовую комплектацию"
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(default=False, help_text="Доступно как опция"),
                ),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="cars.carmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Особенность автомобиля",
                "verbose_name_plural": "Особенности автомобилей",
            },
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
