# Generated by Django 5.2.4 on 2025-08-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_remove_car_dealer_remove_car_supplier_and_more"),
        ("deals", "0004_alter_deal_options_alter_offer_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Car",
        ),
        migrations.DeleteModel(
            name="Promotion",
        ),
        migrations.AlterUniqueTogether(
            name="carfeature",
            unique_together={("car_model", "name")},
        ),
    ]
