# Generated by Django 5.2.5 on 2025-11-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_delete_car_delete_promotion_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carfeature",
            options={
                "ordering": ["car_model", "name"],
                "verbose_name": "Особенность автомобиля",
                "verbose_name_plural": "Особенности автомобилей",
            },
        ),
    ]
